import type { NextConfig } from "next";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Stamp the build id for the suite-wide "Update available" banner. Runs at
// config evaluation, so every build (and dev start) gets a fresh id. Two
// artifacts, same value: public/version.json ships in out/ and is what
// deployed pages poll; lib/build-id.ts is bundled into the client so the
// running page knows which build it IS. (The client must not import from
// public/ — Turbopack's HMR can't model that and wedges the dev runtime.)
const buildId = new Date().toISOString();
mkdirSync(join(__dirname, "public"), { recursive: true });
writeFileSync(join(__dirname, "public", "version.json"), JSON.stringify({ build: buildId }) + "\n");
writeFileSync(
  join(__dirname, "lib", "build-id.ts"),
  `// Generated by next.config.ts at build time — do not edit, do not commit.\nexport const BUILD_ID = ${JSON.stringify(buildId)};\n`
);

const nextConfig: NextConfig = {
  // Fully client-side app — static export deploys straight to Cloudflare Pages
  // (build output: out/).
  output: "export",
};

export default nextConfig;
